package fr.sumomod;

public class ListsMaps {
    static double posX, posY, posZ;
    public static double[][] DefWest12 = {{posX+2, posY, posZ}, {posX+2, posY, posZ+1}, {posX+2, posY, posZ-1}, {posX+2, posY, posZ+2}, {posX+2, posY, posZ-2},
            {posX+1, posY, posZ+3}, {posX+1, posY, posZ-3},
            {posX+1, posY, posZ+4}, {posX+1, posY, posZ-4},
            {posX, posY, posZ+5}, {posX, posY, posZ-5},
            {posX-1, posY, posZ+6}, {posX-1, posY, posZ-6},
            {posX-2, posY, posZ+6}, {posX-2, posY, posZ-6},
            {posX-3, posY, posZ+7}, {posX-3, posY, posZ-7},
            {posX-4, posY, posZ+7}, {posX-4, posY, posZ-7},
            {posX-5, posY, posZ+7}, {posX-5, posY, posZ-7},
            {posX-6, posY, posZ+7}, {posX-6, posY, posZ-7},
            {posX-7, posY, posZ+7}, {posX-7, posY, posZ-7},
            {posX-8, posY, posZ+6}, {posX-8, posY, posZ-6},
            {posX-9, posY, posZ+6}, {posX-9, posY, posZ-6},
            {posX-10, posY, posZ+5}, {posX-10, posY, posZ-5},
            {posX-11, posY, posZ+4}, {posX-11, posY, posZ-4},
            {posX-12, posY, posZ+2}, {posX-12, posY, posZ-2}, {posX-12, posY, posZ+1}, {posX-12, posY, posZ-1},{posX-12, posY, posZ}};
    public static double[][] DefEast12 = {{posX-2, posY, posZ}, {posX-2, posY, posZ+1}, {posX-2, posY, posZ-1}, {posX-2, posY, posZ+2}, {posX-2, posY, posZ-2},
            {posX-1, posY, posZ+3}, {posX-1, posY, posZ-3},
            {posX-1, posY, posZ+4}, {posX-1, posY, posZ-4},
            {posX, posY, posZ+5}, {posX, posY, posZ-5},
            {posX+1, posY, posZ+6}, {posX+1, posY, posZ-6},
            {posX+2, posY, posZ+6}, {posX+2, posY, posZ-6},
            {posX+3, posY, posZ+7}, {posX+3, posY, posZ-7},
            {posX+4, posY, posZ+7}, {posX+4, posY, posZ-7},
            {posX+5, posY, posZ+7}, {posX+5, posY, posZ-7},
            {posX+6, posY, posZ+7}, {posX+6, posY, posZ-7},
            {posX+7, posY, posZ+7}, {posX+7, posY, posZ-7},
            {posX+8, posY, posZ+6}, {posX+8, posY, posZ-6},
            {posX+9, posY, posZ+6}, {posX+9, posY, posZ-6},
            {posX+10, posY, posZ+5}, {posX+10, posY, posZ-5},
            {posX+11, posY, posZ+4}, {posX+11, posY, posZ-4},
            {posX+12, posY, posZ+2}, {posX+12, posY, posZ-2}, {posX+12, posY, posZ+1}, {posX+12, posY, posZ-1},{posX+12, posY, posZ}};
    public static double[][] DefNorth12 = {{posX, posY, posZ+2}, {posX+1, posY, posZ+2}, {posX-1, posY, posZ+2}, {posX-2, posY, posZ+2}, {posX+2, posY, posZ+2},
            {posX+3, posY, posZ+1}, {posX-3, posY, posZ+1},{posX+4, posY, posZ+1}, {posX-4, posY, posZ+1},
            {posX+5, posY, posZ}, {posX-5, posY, posZ},
            {posX+6, posY, posZ-1}, {posX-6, posY, posZ-1},
            {posX+6, posY, posZ-2}, {posX-6, posY, posZ-2},
            {posX+7, posY, posZ-3}, {posX-7, posY, posZ-3},
            {posX+7, posY, posZ-4}, {posX-7, posY, posZ-4},
            {posX+7, posY, posZ-5}, {posX-7, posY, posZ-5},
            {posX+7, posY, posZ-6}, {posX-7, posY, posZ-6},
            {posX+7, posY, posZ-7}, {posX-7, posY, posZ-7},
            {posX+6, posY, posZ-8}, {posX-6, posY, posZ-8},
            {posX+6, posY, posZ-9}, {posX-6, posY, posZ-9},
            {posX+5, posY, posZ-10}, {posX-5, posY, posZ-10},
            {posX+4, posY, posZ-11}, {posX-4, posY, posZ-11},
            {posX+2, posY, posZ-12}, {posX-2, posY, posZ-12},{posX+1, posY, posZ-12}, {posX-1, posY, posZ-12},{posX, posY, posZ-12}};
    public static double[][] DefSouth12 = {{posX, posY, posZ-2}, {posX+1, posY, posZ-2}, {posX-1, posY, posZ-2}, {posX-2, posY, posZ-2}, {posX+2, posY, posZ-2},
            {posX+3, posY, posZ-1}, {posX-3, posY, posZ-1},{posX+4, posY, posZ-1}, {posX-4, posY, posZ-1},
            {posX+5, posY, posZ}, {posX-5, posY, posZ},
            {posX+6, posY, posZ+1}, {posX-6, posY, posZ+1},
            {posX+6, posY, posZ+2}, {posX-6, posY, posZ+2},
            {posX+7, posY, posZ+3}, {posX-7, posY, posZ+3},
            {posX+7, posY, posZ+4}, {posX-7, posY, posZ+4},
            {posX+7, posY, posZ+5}, {posX-7, posY, posZ+5},
            {posX+7, posY, posZ+6}, {posX-7, posY, posZ+6},
            {posX+7, posY, posZ+7}, {posX-7, posY, posZ+7},
            {posX+6, posY, posZ+8}, {posX-6, posY, posZ+8},
            {posX+6, posY, posZ+9}, {posX-6, posY, posZ+9},
            {posX+5, posY, posZ+10}, {posX-5, posY, posZ+10},
            {posX+4, posY, posZ+11}, {posX-4, posY, posZ+11},
            {posX+2, posY, posZ+12}, {posX-2, posY, posZ+12},{posX+1, posY, posZ+12}, {posX-1, posY, posZ+12},{posX, posY, posZ+12}};
    public static double[][] DefNorth10 = {{posX, posY, posZ + 2}, {posX + 1, posY, posZ + 2}, {posX - 1, posY, posZ + 2}, {posX + 2, posY, posZ + 2}, {posX - 2, posY, posZ + 2},
            {posX + 3, posY, posZ + 1}, {posX - 3, posY, posZ + 1}, {posX + 4, posY, posZ + 1}, {posX - 4, posY, posZ + 1},
            {posX + 5, posY, posZ}, {posX - 5, posY, posZ},
            {posX + 5, posY, posZ - 1}, {posX - 5, posY, posZ - 1},
            {posX + 6, posY, posZ - 2}, {posX - 6, posY, posZ - 2},
            {posX + 6, posY, posZ - 3}, {posX - 6, posY, posZ - 3},
            {posX + 6, posY, posZ - 4}, {posX - 6, posY, posZ - 4},
            {posX + 6, posY, posZ - 5}, {posX - 6, posY, posZ - 5},
            {posX + 6, posY, posZ - 6}, {posX - 6, posY, posZ - 6},
            {posX + 5, posY, posZ - 7}, {posX - 5, posY, posZ - 7},
            {posX + 5, posY, posZ - 8}, {posX - 5, posY, posZ - 8},
            {posX + 4, posY, posZ - 9}, {posX - 4, posY, posZ - 9},
            {posX + 2, posY, posZ - 10}, {posX - 2, posY, posZ - 10}, {posX + 1, posY, posZ - 10}, {posX - 1, posY, posZ - 10}, {posX, posY, posZ - 10}};
    public static double[][] DefSouth10 = {{posX, posY, posZ - 2}, {posX + 1, posY, posZ - 2}, {posX - 1, posY, posZ - 2}, {posX + 2, posY, posZ - 2}, {posX - 2, posY, posZ - 2},
            {posX + 3, posY, posZ - 1}, {posX - 3, posY, posZ - 1}, {posX + 4, posY, posZ - 1}, {posX - 4, posY, posZ - 1},
            {posX + 5, posY, posZ}, {posX - 5, posY, posZ},
            {posX + 5, posY, posZ + 1}, {posX - 5, posY, posZ + 1},
            {posX + 6, posY, posZ + 2}, {posX - 6, posY, posZ + 2},
            {posX + 6, posY, posZ + 3}, {posX - 6, posY, posZ + 3},
            {posX + 6, posY, posZ + 4}, {posX - 6, posY, posZ + 4},
            {posX + 6, posY, posZ + 5}, {posX - 6, posY, posZ + 5},
            {posX + 6, posY, posZ + 6}, {posX - 6, posY, posZ + 6},
            {posX + 5, posY, posZ + 7}, {posX - 5, posY, posZ + 7},
            {posX + 5, posY, posZ + 8}, {posX - 5, posY, posZ + 8},
            {posX + 4, posY, posZ + 9}, {posX - 4, posY, posZ + 9},
            {posX + 2, posY, posZ + 10}, {posX - 2, posY, posZ + 10}, {posX + 1, posY, posZ + 10}, {posX - 1, posY, posZ + 10}, {posX, posY, posZ + 10}};
    public static double[][] DefEast10 = {{posX-2, posY, posZ}, {posX-2, posY, posZ+1}, {posX-2, posY, posZ-1},{posX-2, posY, posZ+2}, {posX-2, posY, posZ-2},
            {posX-1, posY, posZ+3}, {posX-1, posY, posZ-3}, {posX-1, posY, posZ+4}, {posX-1, posY, posZ-4},
            {posX, posY, posZ+5}, {posX, posY, posZ-5},
            {posX+1, posY, posZ+5}, {posX+1, posY, posZ-5},
            {posX+2, posY, posZ+6}, {posX+2, posY, posZ-6},
            {posX+3, posY, posZ+6}, {posX+3, posY, posZ-6},
            {posX+4, posY, posZ+6}, {posX+4, posY, posZ-6},
            {posX+5, posY, posZ+6}, {posX+5, posY, posZ-6},
            {posX+6, posY, posZ+6}, {posX+6, posY, posZ-6},
            {posX+7, posY, posZ+5}, {posX+7, posY, posZ-5},
            {posX+8, posY, posZ+5}, {posX+8, posY, posZ-5},
            {posX+9, posY, posZ+4}, {posX+9, posY, posZ-4},
            {posX+10, posY, posZ+2}, {posX+10, posY, posZ-2}, {posX+10, posY, posZ+1}, {posX+10, posY, posZ-1}, {posX+10, posY, posZ}};
    public static double[][] DefWest10 = {{posX+2, posY, posZ}, {posX+2, posY, posZ+1}, {posX+2, posY, posZ-1},{posX+2, posY, posZ+2}, {posX+2, posY, posZ-2},
            {posX+1, posY, posZ+3}, {posX+1, posY, posZ-3}, {posX+1, posY, posZ+4}, {posX+1, posY, posZ-4},
            {posX, posY, posZ+5}, {posX, posY, posZ-5},
            {posX-1, posY, posZ+5}, {posX-1, posY, posZ-5},
            {posX-2, posY, posZ+6}, {posX-2, posY, posZ-6},
            {posX-3, posY, posZ+6}, {posX-3, posY, posZ-6},
            {posX-4, posY, posZ+6}, {posX-4, posY, posZ-6},
            {posX-5, posY, posZ+6}, {posX-5, posY, posZ-6},
            {posX-6, posY, posZ+6}, {posX-6, posY, posZ-6},
            {posX-7, posY, posZ+5}, {posX-7, posY, posZ-5},
            {posX-8, posY, posZ+5}, {posX-8, posY, posZ-5},
            {posX-9, posY, posZ+4}, {posX-9, posY, posZ-4},
            {posX-10, posY, posZ+2}, {posX-10, posY, posZ-2}, {posX-10, posY, posZ+1}, {posX-10, posY, posZ-1}, {posX-10, posY, posZ}};
    public void Seaside() {
        double[][] SeasideNorth = {{posX, posY, posZ + 2}, {posX + 1, posY, posZ + 2}, {posX - 1, posY, posZ + 2}, {posX + 2, posY, posZ + 2}, {posX - 2, posY, posZ + 2},
                {posX + 3, posY, posZ + 1}, {posX - 3, posY, posZ + 1}, {posX + 4, posY, posZ + 1}, {posX - 4, posY, posZ + 1},
                {posX + 5, posY, posZ}, {posX - 5, posY, posZ},
                {posX + 5, posY, posZ - 1}, {posX - 5, posY, posZ - 1},
                {posX + 6, posY, posZ - 2}, {posX - 6, posY, posZ - 2},
                {posX + 6, posY, posZ - 3}, {posX - 6, posY, posZ - 3},
                {posX + 6, posY, posZ - 4}, {posX - 6, posY, posZ - 4},
                {posX + 6, posY, posZ - 5}, {posX - 6, posY, posZ - 5},
                {posX + 6, posY, posZ - 6}, {posX - 6, posY, posZ - 6},
                {posX + 5, posY, posZ - 7}, {posX - 5, posY, posZ - 7},
                {posX + 5, posY, posZ - 8}, {posX - 5, posY, posZ - 8},
                {posX + 4, posY, posZ - 9}, {posX - 4, posY, posZ - 9},
                {posX + 2, posY, posZ - 10}, {posX - 2, posY, posZ - 10}, {posX + 1, posY, posZ - 10}, {posX - 1, posY, posZ - 10}, {posX, posY, posZ - 10}
        };
        double[][] SeasideSouth = {{posX, posY, posZ - 2}, {posX + 1, posY, posZ - 2}, {posX - 1, posY, posZ - 2}, {posX + 2, posY, posZ - 2}, {posX - 2, posY, posZ - 2},
                {posX + 3, posY, posZ - 1}, {posX - 3, posY, posZ - 1}, {posX + 4, posY, posZ - 1}, {posX - 4, posY, posZ - 1},
                {posX + 5, posY, posZ}, {posX - 5, posY, posZ},
                {posX + 5, posY, posZ + 1}, {posX - 5, posY, posZ + 1},
                {posX + 6, posY, posZ + 2}, {posX - 6, posY, posZ + 2},
                {posX + 6, posY, posZ + 3}, {posX - 6, posY, posZ + 3},
                {posX + 6, posY, posZ + 4}, {posX - 6, posY, posZ + 4},
                {posX + 6, posY, posZ + 5}, {posX - 6, posY, posZ + 5},
                {posX + 6, posY, posZ + 6}, {posX - 6, posY, posZ + 6},
                {posX + 5, posY, posZ + 7}, {posX - 5, posY, posZ + 7},
                {posX + 5, posY, posZ + 8}, {posX - 5, posY, posZ + 8},
                {posX + 4, posY, posZ + 9}, {posX - 4, posY, posZ + 9},
                {posX + 2, posY, posZ + 10}, {posX - 2, posY, posZ + 10}, {posX + 1, posY, posZ + 10}, {posX - 1, posY, posZ + 10}, {posX, posY, posZ + 10}};
        double[][] SeasideEast = {{posX-2, posY, posZ}, {posX-2, posY, posZ+1}, {posX-2, posY, posZ-1}, {posX-2, posY, posZ+2}, {posX-2, posY, posZ-2},
                {posX-1, posY, posZ+3}, {posX-1, posY, posZ-3}, {posX-1, posY, posZ+4}, {posX-1, posY, posZ-4},
                {posX, posY, posZ+5}, {posX, posY, posZ-5},
                {posX+1, posY, posZ+6}, {posX+2, posY, posZ-6},
                {posX+2, posY, posZ+6}, {posX+2, posY, posZ-6},
                {posX+3, posY, posZ+7}, {posX+3, posY, posZ-7},
                {posX+4, posY, posZ+7}, {posX+4, posY, posZ-7},
                {posX+5, posY, posZ+7}, {posX+5, posY, posZ-7},
                {posX+6, posY, posZ+7}, {posX+6, posY, posZ-7},
                {posX+7, posY, posZ+7}, {posX+7, posY, posZ-7},
                {posX+8, posY, posZ+6}, {posX+8, posY, posZ-6},
                {posX+9, posY, posZ+6}, {posX+9, posY, posZ-6},
                {posX+10, posY, posZ+5}, {posX+10, posY, posZ-5},
                {posX+11, posY, posZ+4}, {posX+11, posY, posZ-4},
                {posX+12, posY, posZ+2}, {posX+12, posY, posZ-2},
                {posX+12, posY, posZ+1}, {posX+12, posY, posZ-1},
                {posX+12, posY, posZ}
        }; // Prob not working
    }// North & South 10
    public void Boxing(){
        double[][] BoxingNorth = {{posX, posY, posZ+2},{posX+1, posY, posZ+2},{posX-1, posY, posZ+2},{posX+2, posY, posZ+2},{posX-2, posY, posZ+2},
                {posX+3, posY, posZ+1},{posX-3, posY, posZ+1},
                {posX+4, posY, posZ},{posX-4, posY, posZ},
                {posX+5, posY, posZ-1},{posX-5, posY, posZ-1},
                {posX+6, posY, posZ-2},{posX-6, posY, posZ-2},
                {posX+6, posY, posZ-3},{posX-6, posY, posZ-3},
                {posX+6, posY, posZ-4},{posX-6, posY, posZ-4},
                {posX+6, posY, posZ-5},{posX-6, posY, posZ-5},
                {posX+6, posY, posZ-6},{posX-6, posY, posZ-6},
                {posX+6, posY, posZ-7},{posX-6, posY, posZ-7},
                {posX+6, posY, posZ-8},{posX-6, posY, posZ-8},
                {posX+5, posY, posZ-9},{posX-5, posY, posZ-9},
                {posX+4, posY, posZ-10},{posX-4, posY, posZ-10},
                {posX+3, posY, posZ-11},{posX-3, posY, posZ-11},
                {posX+2, posY, posZ-12},{posX-2, posY, posZ-12},{posX+1, posY, posZ-12},{posX-1, posY, posZ-12},{posX, posY, posZ-12}
        };
        double[][] BoxingSouth ={{posX, posY, posZ-2},{posX+1, posY, posZ-2},{posX-1, posY, posZ-2},{posX+2, posY, posZ-2},{posX-2, posY, posZ-2},
                {posX+3, posY, posZ-1},{posX-3, posY, posZ-1},
                {posX+4, posY, posZ},{posX-4, posY, posZ},
                {posX+5, posY, posZ+1},{posX-5, posY, posZ+1},
                {posX+6, posY, posZ+2},{posX-6, posY, posZ+2},
                {posX+6, posY, posZ+3},{posX-6, posY, posZ+3},
                {posX+6, posY, posZ+4},{posX-6, posY, posZ+4},
                {posX+6, posY, posZ+5},{posX-6, posY, posZ+5},
                {posX+6, posY, posZ+6},{posX-6, posY, posZ+6},
                {posX+6, posY, posZ+7},{posX-6, posY, posZ+7},
                {posX+6, posY, posZ+8},{posX-6, posY, posZ+8},
                {posX+5, posY, posZ+9},{posX-5, posY, posZ+9},
                {posX+4, posY, posZ+10},{posX-4, posY, posZ+10},
                {posX+3, posY, posZ+11},{posX-3, posY, posZ+11},
                {posX+2, posY, posZ+12},{posX-2, posY, posZ+12},{posX+1, posY, posZ+12},{posX-1, posY, posZ+12},{posX, posY, posZ+12}
        };
    } // North & South 12
    public void Imperial(){
        double[][] ImperialSouth ={{posX, posY, posZ-2}, {posX+1, posY, posZ-2}, {posX-1, posY, posZ-2}, {posX-2, posY, posZ-2}, {posX+2, posY, posZ-2},
                {posX+3, posY, posZ-1}, {posX-3, posY, posZ-1},{posX+4, posY, posZ-1}, {posX-4, posY, posZ-1},
                {posX+5, posY, posZ}, {posX-5, posY, posZ},
                {posX+6, posY, posZ+1}, {posX-6, posY, posZ+1},
                {posX+6, posY, posZ+2}, {posX-6, posY, posZ+2},
                {posX+7, posY, posZ+3}, {posX-7, posY, posZ+3},
                {posX+7, posY, posZ+4}, {posX-7, posY, posZ+4},
                {posX+7, posY, posZ+5}, {posX-7, posY, posZ+5},
                {posX+7, posY, posZ+6}, {posX-7, posY, posZ+6},
                {posX+7, posY, posZ+7}, {posX-7, posY, posZ+7},
                {posX+6, posY, posZ+8}, {posX-6, posY, posZ+8},
                {posX+6, posY, posZ+9}, {posX-6, posY, posZ+9},
                {posX+5, posY, posZ+10}, {posX-5, posY, posZ+10},
                {posX+4, posY, posZ+11}, {posX-4, posY, posZ+11},
                {posX+2, posY, posZ+12}, {posX-2, posY, posZ+12},{posX+1, posY, posZ+12}, {posX-1, posY, posZ+12},{posX, posY, posZ+12}
        };
        double[][] ImperialNorth = {{posX, posY, posZ+2}, {posX+1, posY, posZ+2}, {posX-1, posY, posZ+2}, {posX-2, posY, posZ+2}, {posX+2, posY, posZ+2},
                {posX+3, posY, posZ+1}, {posX-3, posY, posZ+1},{posX+4, posY, posZ+1}, {posX-4, posY, posZ+1},
                {posX+5, posY, posZ}, {posX-5, posY, posZ},
                {posX+6, posY, posZ-1}, {posX-6, posY, posZ-1},
                {posX+6, posY, posZ-2}, {posX-6, posY, posZ-2},
                {posX+7, posY, posZ-3}, {posX-7, posY, posZ-3},
                {posX+7, posY, posZ-4}, {posX-7, posY, posZ-4},
                {posX+7, posY, posZ-5}, {posX-7, posY, posZ-5},
                {posX+7, posY, posZ-6}, {posX-7, posY, posZ-6},
                {posX+7, posY, posZ-7}, {posX-7, posY, posZ-7},
                {posX+6, posY, posZ-8}, {posX-6, posY, posZ-8},
                {posX+6, posY, posZ-9}, {posX-6, posY, posZ-9},
                {posX+5, posY, posZ-10}, {posX-5, posY, posZ-10},
                {posX+4, posY, posZ-11}, {posX-4, posY, posZ-11},
                {posX+2, posY, posZ-12}, {posX-2, posY, posZ-12},{posX+1, posY, posZ-12}, {posX-1, posY, posZ-12},{posX, posY, posZ-12}
        };
    } // North & South 12
    public void PokeBall(){
        double[][] PokeBallSouth = {{posX, posY, posZ-3}, {posX+1, posY, posZ-3}, {posX-1, posY, posZ-3}, {posX+2, posY, posZ-3}, {posX-2, posY, posZ-3},
                {posX+3, posY, posZ-2}, {posX-3, posY, posZ-2}, {posX+4, posY, posZ-2}, {posX-4, posY, posZ-2},
                {posX+5, posY, posZ-1}, {posX-5, posY, posZ-1},
                {posX+6, posY, posZ}, {posX-6, posY, posZ},
                {posX+7, posY, posZ+1}, {posX-7, posY, posZ+1},
                {posX+7, posY, posZ+2}, {posX-7, posY, posZ+2},
                {posX+8, posY, posZ+3}, {posX-8, posY, posZ+3},
                {posX+8, posY, posZ+4}, {posX-8, posY, posZ+4},
                {posX+8, posY, posZ+5}, {posX-8, posY, posZ+5},
                {posX+8, posY, posZ+6}, {posX-8, posY, posZ+6},
                {posX+8, posY, posZ+7}, {posX-8, posY, posZ+7},
                {posX+7, posY, posZ+8}, {posX-7, posY, posZ+8},
                {posX+7, posY, posZ+9}, {posX-7, posY, posZ+9},
                {posX+6, posY, posZ+10}, {posX-6, posY, posZ+10},
                {posX+5, posY, posZ+11}, {posX-5, posY, posZ+11},
                {posX+4, posY, posZ+12}, {posX-4, posY, posZ+12}, {posX+3, posY, posZ+12}, {posX-3, posY, posZ+12},
                {posX+2, posY, posZ+13}, {posX-2, posY, posZ+13}, {posX+1, posY, posZ+13}, {posX-1, posY, posZ+13}, {posX, posY, posZ+13}
        };
        double[][] PokeBallNorth = {{posX, posY, posZ+3}, {posX+1, posY, posZ+3}, {posX-1, posY, posZ+3}, {posX+2, posY, posZ+3}, {posX-2, posY, posZ+3},
                {posX+3, posY, posZ+2}, {posX-3, posY, posZ+2}, {posX+4, posY, posZ+2}, {posX-4, posY, posZ+2},
                {posX+5, posY, posZ+1}, {posX-5, posY, posZ+1},
                {posX+6, posY, posZ}, {posX-6, posY, posZ},
                {posX+7, posY, posZ-1}, {posX-7, posY, posZ-1},
                {posX+7, posY, posZ-2}, {posX-7, posY, posZ-2},
                {posX+8, posY, posZ-3}, {posX-8, posY, posZ-3},
                {posX+8, posY, posZ-4}, {posX-8, posY, posZ-4},
                {posX+8, posY, posZ-5}, {posX-8, posY, posZ-5},
                {posX+8, posY, posZ-6}, {posX-8, posY, posZ-6},
                {posX+8, posY, posZ-7}, {posX-8, posY, posZ-7},
                {posX+7, posY, posZ-8}, {posX-7, posY, posZ-8},
                {posX+7, posY, posZ-9}, {posX-7, posY, posZ-9},
                {posX+6, posY, posZ-10}, {posX-6, posY, posZ-10},
                {posX+5, posY, posZ-11}, {posX-5, posY, posZ-11},
                {posX+4, posY, posZ-12}, {posX-4, posY, posZ-12}, {posX+3, posY, posZ-12}, {posX-3, posY, posZ-12},
                {posX+2, posY, posZ-13}, {posX-2, posY, posZ-13}, {posX+1, posY, posZ-13}, {posX-1, posY, posZ-13}, {posX, posY, posZ-13}
        };
    } // North & South 13???
    public void Tropical(){
        double[][] TropicalSouth = {{posX, posY, posZ-2}, {posX+1, posY, posZ-2}, {posX-1, posY, posZ-2}, {posX-2, posY, posZ-2}, {posX+2, posY, posZ-2},
                {posX+3, posY, posZ-1}, {posX-3, posY, posZ-1},{posX+4, posY, posZ-1}, {posX-4, posY, posZ-1},
                {posX+5, posY, posZ}, {posX-5, posY, posZ},
                {posX+6, posY, posZ+1}, {posX-6, posY, posZ+1},
                {posX+6, posY, posZ+2}, {posX-6, posY, posZ+2},
                {posX+7, posY, posZ+3}, {posX-7, posY, posZ+3},
                {posX+7, posY, posZ+4}, {posX-7, posY, posZ+4},
                {posX+7, posY, posZ+5}, {posX-7, posY, posZ+5},
                {posX+7, posY, posZ+6}, {posX-7, posY, posZ+6},
                {posX+7, posY, posZ+7}, {posX-7, posY, posZ+7},
                {posX+6, posY, posZ+8}, {posX-6, posY, posZ+8},
                {posX+6, posY, posZ+9}, {posX-6, posY, posZ+9},
                {posX+5, posY, posZ+10}, {posX-5, posY, posZ+10},
                {posX+4, posY, posZ+11}, {posX-4, posY, posZ+11},
                {posX+2, posY, posZ+12}, {posX-2, posY, posZ+12},{posX+1, posY, posZ+12}, {posX-1, posY, posZ+12},{posX, posY, posZ+12}
        };
        double[][] TropicalNorth = {{posX, posY, posZ+2}, {posX+1, posY, posZ+2}, {posX-1, posY, posZ+2}, {posX-2, posY, posZ+2}, {posX+2, posY, posZ+2},
                {posX+3, posY, posZ+1}, {posX-3, posY, posZ+1},{posX+4, posY, posZ+1}, {posX-4, posY, posZ+1},
                {posX+5, posY, posZ}, {posX-5, posY, posZ},
                {posX+6, posY, posZ-1}, {posX-6, posY, posZ-1},
                {posX+6, posY, posZ-2}, {posX-6, posY, posZ-2},
                {posX+7, posY, posZ-3}, {posX-7, posY, posZ-3},
                {posX+7, posY, posZ-4}, {posX-7, posY, posZ-4},
                {posX+7, posY, posZ-5}, {posX-7, posY, posZ-5},
                {posX+7, posY, posZ-6}, {posX-7, posY, posZ-6},
                {posX+7, posY, posZ-7}, {posX-7, posY, posZ-7},
                {posX+6, posY, posZ-8}, {posX-6, posY, posZ-8},
                {posX+6, posY, posZ-9}, {posX-6, posY, posZ-9},
                {posX+5, posY, posZ-10}, {posX-5, posY, posZ-10},
                {posX+4, posY, posZ-11}, {posX-4, posY, posZ-11},
                {posX+2, posY, posZ-12}, {posX-2, posY, posZ-12},{posX+1, posY, posZ-12}, {posX-1, posY, posZ-12},{posX, posY, posZ-12}
        };
    } // North & South 12
    public void Overgrown(){
        double[][] OvergrownSouth = {{posX, posY, posZ-2}, {posX+1, posY, posZ-2}, {posX+2, posY, posZ-2}, {posX-1, posY, posZ-2}, {posX-2, posY, posZ-2},
                {posX+3, posY, posZ-1}, {posX-3, posY, posZ-1}, {posX-4, posY, posZ-1}, {posX+4, posY, posZ-1},
                {posX+4, posY, posZ}, {posX-4, posY, posZ}, {posX+5, posY, posZ}, {posX-5, posY, posZ},
                {posX+5, posY, posZ+1}, {posX-5, posY, posZ+1},
                {posX+6, posY, posZ+2}, {posX-6, posY, posZ+2},
                {posX+6, posY, posZ+3}, {posX-6, posY, posZ+3},
                {posX+6, posY, posZ+4}, {posX-6, posY, posZ+4},
                {posX+6, posY, posZ+5}, {posX-6, posY, posZ+5},
                {posX+6, posY, posZ+6}, {posX-6, posY, posZ+6},
                {posX+5, posY, posZ+7}, {posX-5, posY, posZ+7},
                {posX+5, posY, posZ+8}, {posX-5, posY, posZ+8}, {posX+4, posY, posZ+8}, {posX-4, posY, posZ+8},
                {posX+4, posY, posZ+9}, {posX-4, posY, posZ+9}, {posX+3, posY, posZ+9}, {posX-3, posY, posZ+9},
                {posX+2, posY, posZ+10}, {posX-2, posY, posZ+10},
                {posX+1, posY, posZ+10}, {posX-1, posY, posZ+10}, {posX, posY, posZ+10}
        };
        double[][] OvergrownNorth = {{posX, posY, posZ+2}, {posX+1, posY, posZ+2}, {posX+2, posY, posZ+2}, {posX-1, posY, posZ+2}, {posX-2, posY, posZ+2},
                {posX+3, posY, posZ+1}, {posX-3, posY, posZ+1}, {posX-4, posY, posZ+1}, {posX+4, posY, posZ+1},
                {posX+4, posY, posZ}, {posX-4, posY, posZ}, {posX+5, posY, posZ}, {posX-5, posY, posZ},
                {posX+5, posY, posZ-1}, {posX-5, posY, posZ-1},
                {posX+6, posY, posZ-2}, {posX-6, posY, posZ-2},
                {posX+6, posY, posZ-3}, {posX-6, posY, posZ-3},
                {posX+6, posY, posZ-4}, {posX-6, posY, posZ-4},
                {posX+6, posY, posZ-5}, {posX-6, posY, posZ-5},
                {posX+6, posY, posZ-6}, {posX-6, posY, posZ-6},
                {posX+5, posY, posZ-7}, {posX-5, posY, posZ-7},
                {posX+5, posY, posZ-8}, {posX-5, posY, posZ-8}, {posX+4, posY, posZ-8}, {posX-4, posY, posZ-8},
                {posX+4, posY, posZ-9}, {posX-4, posY, posZ-9}, {posX+3, posY, posZ-9}, {posX-3, posY, posZ-9},
                {posX+2, posY, posZ-10}, {posX-2, posY, posZ-10},
                {posX+1, posY, posZ-10}, {posX-1, posY, posZ-10}, {posX, posY, posZ-10}
        };
    } // North & South 10
    public void Watermelon(){
        double [][] WatermelonSouth = {{posX, posY, posZ-2},{posX+1, posY, posZ-2},{posX-1, posY, posZ-2},{posX+2, posY, posZ-2},{posX-2, posY, posZ-2},
                {posX+3, posY, posZ-1}, {posX-3, posY, posZ-1},
                {posX+4, posY, posZ}, {posX-4, posY, posZ},
                {posX+5, posY, posZ+1}, {posX-5, posY, posZ+1},
                {posX+6, posY, posZ+2}, {posX-6, posY, posZ+2},
                {posX+6, posY, posZ+3}, {posX-6, posY, posZ+3},
                {posX+6, posY, posZ+4}, {posX-6, posY, posZ+4},
                {posX+6, posY, posZ+5}, {posX-6, posY, posZ+5},
                {posX+6, posY, posZ+6}, {posX-6, posY, posZ+6},
                {posX+5, posY, posZ+7}, {posX-5, posY, posZ+7},
                {posX+4, posY, posZ+8}, {posX-4, posY, posZ+8},
                {posX+3, posY, posZ+9}, {posX-3, posY, posZ+9},
                {posX+2, posY, posZ+10}, {posX-2, posY, posZ+10}, {posX+1, posY, posZ+10}, {posX-1, posY, posZ+10}, {posX, posY, posZ+10}
        };
        double [][] WatermelonNorth = {{posX, posY, posZ+2},{posX+1, posY, posZ+2},{posX-1, posY, posZ+2},{posX+2, posY, posZ+2},{posX-2, posY, posZ+2},
                {posX+3, posY, posZ+1}, {posX-3, posY, posZ+1},
                {posX+4, posY, posZ}, {posX-4, posY, posZ},
                {posX+5, posY, posZ-1}, {posX-5, posY, posZ-1},
                {posX+6, posY, posZ-2}, {posX-6, posY, posZ-2},
                {posX+6, posY, posZ-3}, {posX-6, posY, posZ-3},
                {posX+6, posY, posZ-4}, {posX-6, posY, posZ-4},
                {posX+6, posY, posZ-5}, {posX-6, posY, posZ-5},
                {posX+6, posY, posZ-6}, {posX-6, posY, posZ-6},
                {posX+5, posY, posZ-7}, {posX-5, posY, posZ-7},
                {posX+4, posY, posZ-8}, {posX-4, posY, posZ-8},
                {posX+3, posY, posZ-9}, {posX-3, posY, posZ-9},
                {posX+2, posY, posZ-10}, {posX-2, posY, posZ-10}, {posX+1, posY, posZ-10}, {posX-1, posY, posZ-10}, {posX, posY, posZ-10}
        };
    } // North & South 10
    public void Ruins(){
        double [][] RuinsSouth = {
                {posX, posY, posZ-2}, {posX+1, posY, posZ-2}, {posX+2, posY, posZ-2}, {posX-1, posY, posZ-2}, {posX-2, posY, posZ-2},
                {posX+3, posY, posZ-1}, {posX-3, posY, posZ-1}, {posX-4, posY, posZ-1}, {posX+4, posY, posZ-1},
                {posX+4, posY, posZ}, {posX-4, posY, posZ}, {posX+5, posY, posZ}, {posX-5, posY, posZ},
                {posX+5, posY, posZ+1}, {posX-5, posY, posZ+1},
                {posX+6, posY, posZ+2}, {posX-6, posY, posZ+2},
                {posX+6, posY, posZ+3}, {posX-6, posY, posZ+3},
                {posX+6, posY, posZ+4}, {posX-6, posY, posZ+4},
                {posX+6, posY, posZ+5}, {posX-6, posY, posZ+5},
                {posX+6, posY, posZ+6}, {posX-6, posY, posZ+6},
                {posX+5, posY, posZ+7}, {posX-5, posY, posZ+7},
                {posX+5, posY, posZ+8}, {posX-5, posY, posZ+8}, {posX+4, posY, posZ+8}, {posX-4, posY, posZ+8},
                {posX+4, posY, posZ+9}, {posX-4, posY, posZ+9}, {posX+3, posY, posZ+9}, {posX-3, posY, posZ+9},
                {posX+2, posY, posZ+10}, {posX-2, posY, posZ+10},
                {posX+1, posY, posZ+10}, {posX-1, posY, posZ+10}, {posX, posY, posZ+10}
        };
        double [][] RuinsNorth = {
                {posX, posY, posZ+2}, {posX+1, posY, posZ+2}, {posX+2, posY, posZ+2}, {posX-1, posY, posZ+2}, {posX-2, posY, posZ+2},
                {posX+3, posY, posZ+1}, {posX-3, posY, posZ+1}, {posX-4, posY, posZ+1}, {posX+4, posY, posZ+1},
                {posX+4, posY, posZ}, {posX-4, posY, posZ}, {posX+5, posY, posZ}, {posX-5, posY, posZ},
                {posX+5, posY, posZ-1}, {posX-5, posY, posZ-1},
                {posX+6, posY, posZ-2}, {posX-6, posY, posZ-2},
                {posX+6, posY, posZ-3}, {posX-6, posY, posZ-3},
                {posX+6, posY, posZ-4}, {posX-6, posY, posZ-4},
                {posX+6, posY, posZ-5}, {posX-6, posY, posZ-5},
                {posX+6, posY, posZ-6}, {posX-6, posY, posZ-6},
                {posX+5, posY, posZ-7}, {posX-5, posY, posZ-7},
                {posX+5, posY, posZ-8}, {posX-5, posY, posZ-8}, {posX+4, posY, posZ-8}, {posX-4, posY, posZ-8},
                {posX+4, posY, posZ-9}, {posX-4, posY, posZ-9}, {posX+3, posY, posZ-9}, {posX-3, posY, posZ-9},
                {posX+2, posY, posZ-10}, {posX-2, posY, posZ-10},
                {posX+1, posY, posZ-10}, {posX-1, posY, posZ-10}, {posX, posY, posZ-10}
        };
    } // North & South 10
    public void Riverside(){
        double[][] RiversideEast = {{posX-2, posY, posZ}, {posX-2, posY, posZ+1}, {posX-2, posY, posZ-1}, {posX-2, posY, posZ+2}, {posX-2, posY, posZ-2},
                {posX-1, posY, posZ+3}, {posX-1, posY, posZ-3},
                {posX-1, posY, posZ+4}, {posX-1, posY, posZ-4},
                {posX, posY, posZ+5}, {posX, posY, posZ-5},
                {posX+1, posY, posZ+6}, {posX+1, posY, posZ-6},
                {posX+2, posY, posZ+6}, {posX+2, posY, posZ-6},
                {posX+3, posY, posZ+7}, {posX+3, posY, posZ-7},
                {posX+4, posY, posZ+7}, {posX+4, posY, posZ-7},
                {posX+5, posY, posZ+7}, {posX+5, posY, posZ-7},
                {posX+6, posY, posZ+7}, {posX+6, posY, posZ-7},
                {posX+7, posY, posZ+7}, {posX+7, posY, posZ-7},
                {posX+8, posY, posZ+6}, {posX+8, posY, posZ-6},
                {posX+9, posY, posZ+6}, {posX+9, posY, posZ-6},
                {posX+10, posY, posZ+5}, {posX+10, posY, posZ-5},
                {posX+11, posY, posZ+4}, {posX+11, posY, posZ-4},
                {posX+12, posY, posZ+2}, {posX+12, posY, posZ-2}, {posX+12, posY, posZ+1}, {posX+12, posY, posZ-1},{posX+12, posY, posZ}
        };
        double[][] RiversideWest = {{posX+2, posY, posZ}, {posX+2, posY, posZ+1}, {posX+2, posY, posZ-1}, {posX+2, posY, posZ+2}, {posX+2, posY, posZ-2},
                {posX+1, posY, posZ+3}, {posX+1, posY, posZ-3},
                {posX+1, posY, posZ+4}, {posX+1, posY, posZ-4},
                {posX, posY, posZ+5}, {posX, posY, posZ-5},
                {posX-1, posY, posZ+6}, {posX-1, posY, posZ-6},
                {posX-2, posY, posZ+6}, {posX-2, posY, posZ-6},
                {posX-3, posY, posZ+7}, {posX-3, posY, posZ-7},
                {posX-4, posY, posZ+7}, {posX-4, posY, posZ-7},
                {posX-5, posY, posZ+7}, {posX-5, posY, posZ-7},
                {posX-6, posY, posZ+7}, {posX-6, posY, posZ-7},
                {posX-7, posY, posZ+7}, {posX-7, posY, posZ-7},
                {posX-8, posY, posZ+6}, {posX-8, posY, posZ-6},
                {posX-9, posY, posZ+6}, {posX-9, posY, posZ-6},
                {posX-10, posY, posZ+5}, {posX-10, posY, posZ-5},
                {posX-11, posY, posZ+4}, {posX-11, posY, posZ-4},
                {posX-12, posY, posZ+2}, {posX-12, posY, posZ-2}, {posX-12, posY, posZ+1}, {posX-12, posY, posZ-1},{posX-12, posY, posZ}
        };
    } // East & West 12
    public void Plateau(){
        double[][] PlateauSouth = {{posX, posY, posZ-2}, {posX+1, posY, posZ-2}, {posX-1, posY, posZ-2}, {posX+2, posY, posZ-2}, {posX-2, posY, posZ-2},
                {posX+3, posY, posZ-2}, {posX-3, posY, posZ-2}, {posX+4, posY, posZ-2}, {posX-4, posY, posZ-2},
                {posX+5, posY, posZ-1}, {posX-5, posY, posZ-1},
                {posX+6, posY, posZ}, {posX-6, posY, posZ},
                {posX+7, posY, posZ+1}, {posX-7, posY, posZ+1},
                {posX+7, posY, posZ+2}, {posX-7, posY, posZ+2},
                {posX+7, posY, posZ+3}, {posX-7, posY, posZ+3},
                {posX+7, posY, posZ+4}, {posX-7, posY, posZ+4},
                {posX+7, posY, posZ+5}, {posX-7, posY, posZ+5},
                {posX+7, posY, posZ+6}, {posX-7, posY, posZ+6},
                {posX+7, posY, posZ+7}, {posX-7, posY, posZ+7},
                {posX+7, posY, posZ+8}, {posX-7, posY, posZ+8},
                {posX+7, posY, posZ+9}, {posX-7, posY, posZ+9},
                {posX+6, posY, posZ+10}, {posX-6, posY, posZ+10},
                {posX+5, posY, posZ+11}, {posX-5, posY, posZ+11},
                {posX+4, posY, posZ+12}, {posX-4, posY, posZ+12},{posX+3, posY, posZ+12}, {posX-3, posY, posZ+12},{posX+2, posY, posZ+12}, {posX-2, posY, posZ+12},
                {posX+1, posY, posZ+12}, {posX-1, posY, posZ+12},{posX, posY, posZ+12}
        };
        double[][] PlateauNorth = {{posX, posY, posZ+2}, {posX+1, posY, posZ+2}, {posX-1, posY, posZ+2}, {posX+2, posY, posZ+2}, {posX-2, posY, posZ+2},
                {posX+3, posY, posZ+2}, {posX-3, posY, posZ+2}, {posX+4, posY, posZ+2}, {posX-4, posY, posZ+2},
                {posX+5, posY, posZ+1}, {posX-5, posY, posZ+1},
                {posX+6, posY, posZ}, {posX-6, posY, posZ},
                {posX+7, posY, posZ-1}, {posX-7, posY, posZ-1},
                {posX+7, posY, posZ-2}, {posX-7, posY, posZ-2},
                {posX+7, posY, posZ-3}, {posX-7, posY, posZ-3},
                {posX+7, posY, posZ-4}, {posX-7, posY, posZ-4},
                {posX+7, posY, posZ-5}, {posX-7, posY, posZ-5},
                {posX+7, posY, posZ-6}, {posX-7, posY, posZ-6},
                {posX+7, posY, posZ-7}, {posX-7, posY, posZ-7},
                {posX+7, posY, posZ-8}, {posX-7, posY, posZ-8},
                {posX+7, posY, posZ-9}, {posX-7, posY, posZ-9},
                {posX+6, posY, posZ-10}, {posX-6, posY, posZ-10},
                {posX+5, posY, posZ-11}, {posX-5, posY, posZ-11},
                {posX+4, posY, posZ-12}, {posX-4, posY, posZ-12},{posX+3, posY, posZ-12}, {posX-3, posY, posZ-12},{posX+2, posY, posZ-12}, {posX-2, posY, posZ-12},
                {posX+1, posY, posZ-12}, {posX-1, posY, posZ-12},{posX, posY, posZ-12}
        };
    } // North & South 12
    public void Italy(){
        double[][] ItalyEast = {{posX-2, posY, posZ}, {posX-2, posY, posZ+1}, {posX-2, posY, posZ-1}, {posX-2, posY, posZ+2}, {posX-2, posY, posZ-2},
                {posX-1, posY, posZ+3}, {posX-1, posY, posZ-3},
                {posX-1, posY, posZ+4}, {posX-1, posY, posZ-4},
                {posX, posY, posZ+5}, {posX, posY, posZ-5},
                {posX+1, posY, posZ+6}, {posX+1, posY, posZ-6},
                {posX+2, posY, posZ+6}, {posX+2, posY, posZ-6},
                {posX+3, posY, posZ+7}, {posX+3, posY, posZ-7},
                {posX+4, posY, posZ+7}, {posX+4, posY, posZ-7},
                {posX+5, posY, posZ+7}, {posX+5, posY, posZ-7},
                {posX+6, posY, posZ+7}, {posX+6, posY, posZ-7},
                {posX+7, posY, posZ+7}, {posX+7, posY, posZ-7},
                {posX+8, posY, posZ+6}, {posX+8, posY, posZ-6},
                {posX+9, posY, posZ+6}, {posX+9, posY, posZ-6},
                {posX+10, posY, posZ+5}, {posX+10, posY, posZ-5},
                {posX+11, posY, posZ+4}, {posX+11, posY, posZ-4},
                {posX+12, posY, posZ+2}, {posX+12, posY, posZ-2}, {posX+12, posY, posZ+1}, {posX+12, posY, posZ-1},{posX+12, posY, posZ}
        };
        double[][] ItalyWest = {{posX+2, posY, posZ}, {posX+2, posY, posZ+1}, {posX+2, posY, posZ-1}, {posX+2, posY, posZ+2}, {posX+2, posY, posZ-2},
                {posX+1, posY, posZ+3}, {posX+1, posY, posZ-3},
                {posX+1, posY, posZ+4}, {posX+1, posY, posZ-4},
                {posX, posY, posZ+5}, {posX, posY, posZ-5},
                {posX-1, posY, posZ+6}, {posX-1, posY, posZ-6},
                {posX-2, posY, posZ+6}, {posX-2, posY, posZ-6},
                {posX-3, posY, posZ+7}, {posX-3, posY, posZ-7},
                {posX-4, posY, posZ+7}, {posX-4, posY, posZ-7},
                {posX-5, posY, posZ+7}, {posX-5, posY, posZ-7},
                {posX-6, posY, posZ+7}, {posX-6, posY, posZ-7},
                {posX-7, posY, posZ+7}, {posX-7, posY, posZ-7},
                {posX-8, posY, posZ+6}, {posX-8, posY, posZ-6},
                {posX-9, posY, posZ+6}, {posX-9, posY, posZ-6},
                {posX-10, posY, posZ+5}, {posX-10, posY, posZ-5},
                {posX-11, posY, posZ+4}, {posX-11, posY, posZ-4},
                {posX-12, posY, posZ+2}, {posX-12, posY, posZ-2}, {posX-12, posY, posZ+1}, {posX-12, posY, posZ-1},{posX-12, posY, posZ}
        };
    } // East & West 12
    public void DesertTemple(){
        double[][] DesertTempleSouth = {{posX, posY, posZ-2}, {posX+1, posY, posZ-2}, {posX-1, posY, posZ-2}, {posX+2, posY, posZ-2}, {posX-2, posY, posZ-2},

        };
    }
    public void Rose(){
        double[][] RoseNorth = {{posX, posY, posZ + 2}, {posX + 1, posY, posZ + 2}, {posX - 1, posY, posZ + 2}, {posX + 2, posY, posZ + 2}, {posX - 2, posY, posZ + 2},
                {posX + 3, posY, posZ + 1}, {posX - 3, posY, posZ + 1}, {posX + 4, posY, posZ + 1}, {posX - 4, posY, posZ + 1},
                {posX + 5, posY, posZ}, {posX - 5, posY, posZ},
                {posX + 5, posY, posZ - 1}, {posX - 5, posY, posZ - 1},
                {posX + 6, posY, posZ - 2}, {posX - 6, posY, posZ - 2},
                {posX + 6, posY, posZ - 3}, {posX - 6, posY, posZ - 3},
                {posX + 6, posY, posZ - 4}, {posX - 6, posY, posZ - 4},
                {posX + 6, posY, posZ - 5}, {posX - 6, posY, posZ - 5},
                {posX + 6, posY, posZ - 6}, {posX - 6, posY, posZ - 6},
                {posX + 5, posY, posZ - 7}, {posX - 5, posY, posZ - 7},
                {posX + 5, posY, posZ - 8}, {posX - 5, posY, posZ - 8},
                {posX + 4, posY, posZ - 9}, {posX - 4, posY, posZ - 9},
                {posX + 2, posY, posZ - 10}, {posX - 2, posY, posZ - 10}, {posX + 1, posY, posZ - 10}, {posX - 1, posY, posZ - 10}, {posX, posY, posZ - 10}
        };
        double[][] RoseSouth = {{posX, posY, posZ-2},{posX+1, posY, posZ-2},{posX-1, posY, posZ-2},{posX+2, posY, posZ-2},{posX-2, posY, posZ-2},
                {posX+3, posY, posZ-1},{posX-3, posY, posZ-1},{posX+4, posY, posZ-1},{posX-4, posY, posZ-1},
                {posX+5, posY, posZ},{posX-5, posY, posZ},
                {posX+5, posY, posZ+1},{posX-5, posY, posZ+1},
                {posX+6, posY, posZ+2},{posX-6, posY, posZ+2},
                {posX+6, posY, posZ+3},{posX-6, posY, posZ+3},
                {posX+6, posY, posZ+4},{posX-6, posY, posZ+4},
                {posX+6, posY, posZ+5},{posX-6, posY, posZ+5},
                {posX+6, posY, posZ+6},{posX-6, posY, posZ+6},
                {posX+5, posY, posZ+7},{posX-5, posY, posZ+7},
                {posX+5, posY, posZ+8},{posX-5, posY, posZ+8},
                {posX+4, posY, posZ+9},{posX-4, posY, posZ+9},
                {posX+2, posY, posZ+10},{posX-2, posY, posZ+10},{posX+1, posY, posZ+10},{posX-1, posY, posZ+10}, {posX, posY, posZ+10}
        };
    }
    public void Underbrush(){
        double[][] UnderbrushNorth = {{posX, posY, posZ + 2}, {posX + 1, posY, posZ + 2}, {posX - 1, posY, posZ + 2}, {posX + 2, posY, posZ + 2}, {posX - 2, posY, posZ + 2},
                {posX + 3, posY, posZ + 1}, {posX - 3, posY, posZ + 1}, {posX + 4, posY, posZ + 1}, {posX - 4, posY, posZ + 1},
                {posX + 5, posY, posZ}, {posX - 5, posY, posZ},
                {posX + 5, posY, posZ - 1}, {posX - 5, posY, posZ - 1},
                {posX + 6, posY, posZ - 2}, {posX - 6, posY, posZ - 2},
                {posX + 6, posY, posZ - 3}, {posX - 6, posY, posZ - 3},
                {posX + 6, posY, posZ - 4}, {posX - 6, posY, posZ - 4},
                {posX + 6, posY, posZ - 5}, {posX - 6, posY, posZ - 5},
                {posX + 6, posY, posZ - 6}, {posX - 6, posY, posZ - 6},
                {posX + 5, posY, posZ - 7}, {posX - 5, posY, posZ - 7},
                {posX + 5, posY, posZ - 8}, {posX - 5, posY, posZ - 8},
                {posX + 4, posY, posZ - 9}, {posX - 4, posY, posZ - 9},
                {posX + 2, posY, posZ - 10}, {posX - 2, posY, posZ - 10}, {posX + 1, posY, posZ - 10}, {posX - 1, posY, posZ - 10}, {posX, posY, posZ - 10}
        };
        double[][] UnderbrushSouth = {{posX, posY, posZ-2},{posX+1, posY, posZ-2},{posX-1, posY, posZ-2},{posX+2, posY, posZ-2},{posX-2, posY, posZ-2},
                {posX+3, posY, posZ-1},{posX-3, posY, posZ-1},{posX+4, posY, posZ-1},{posX-4, posY, posZ-1},
                {posX+5, posY, posZ},{posX-5, posY, posZ},
                {posX+5, posY, posZ+1},{posX-5, posY, posZ+1},
                {posX+6, posY, posZ+2},{posX-6, posY, posZ+2},
                {posX+6, posY, posZ+3},{posX-6, posY, posZ+3},
                {posX+6, posY, posZ+4},{posX-6, posY, posZ+4},
                {posX+6, posY, posZ+5},{posX-6, posY, posZ+5},
                {posX+6, posY, posZ+6},{posX-6, posY, posZ+6},
                {posX+5, posY, posZ+7},{posX-5, posY, posZ+7},
                {posX+5, posY, posZ+8},{posX-5, posY, posZ+8},
                {posX+4, posY, posZ+9},{posX-4, posY, posZ+9},
                {posX+2, posY, posZ+10},{posX-2, posY, posZ+10},{posX+1, posY, posZ+10},{posX-1, posY, posZ+10}, {posX, posY, posZ+10}
        };
    }
    public void Wreck(){
        double[][] WreckNorth = {{posX, posY, posZ + 2}, {posX + 1, posY, posZ + 2}, {posX - 1, posY, posZ + 2}, {posX + 2, posY, posZ + 2}, {posX - 2, posY, posZ + 2},
                {posX + 3, posY, posZ + 1}, {posX - 3, posY, posZ + 1}, {posX + 4, posY, posZ + 1}, {posX - 4, posY, posZ + 1},
                {posX + 5, posY, posZ}, {posX - 5, posY, posZ},
                {posX + 5, posY, posZ - 1}, {posX - 5, posY, posZ - 1},
                {posX + 6, posY, posZ - 2}, {posX - 6, posY, posZ - 2},
                {posX + 6, posY, posZ - 3}, {posX - 6, posY, posZ - 3},
                {posX + 6, posY, posZ - 4}, {posX - 6, posY, posZ - 4},
                {posX + 6, posY, posZ - 5}, {posX - 6, posY, posZ - 5},
                {posX + 6, posY, posZ - 6}, {posX - 6, posY, posZ - 6},
                {posX + 5, posY, posZ - 7}, {posX - 5, posY, posZ - 7},
                {posX + 5, posY, posZ - 8}, {posX - 5, posY, posZ - 8},
                {posX + 4, posY, posZ - 9}, {posX - 4, posY, posZ - 9},
                {posX + 2, posY, posZ - 10}, {posX - 2, posY, posZ - 10}, {posX + 1, posY, posZ - 10}, {posX - 1, posY, posZ - 10}, {posX, posY, posZ - 10}
        };
        double[][] WreckSouth = {{posX, posY, posZ-2},{posX+1, posY, posZ-2},{posX-1, posY, posZ-2},{posX+2, posY, posZ-2},{posX-2, posY, posZ-2},
                {posX+3, posY, posZ-1},{posX-3, posY, posZ-1},{posX+4, posY, posZ-1},{posX-4, posY, posZ-1},
                {posX+5, posY, posZ},{posX-5, posY, posZ},
                {posX+5, posY, posZ+1},{posX-5, posY, posZ+1},
                {posX+6, posY, posZ+2},{posX-6, posY, posZ+2},
                {posX+6, posY, posZ+3},{posX-6, posY, posZ+3},
                {posX+6, posY, posZ+4},{posX-6, posY, posZ+4},
                {posX+6, posY, posZ+5},{posX-6, posY, posZ+5},
                {posX+6, posY, posZ+6},{posX-6, posY, posZ+6},
                {posX+5, posY, posZ+7},{posX-5, posY, posZ+7},
                {posX+5, posY, posZ+8},{posX-5, posY, posZ+8},
                {posX+4, posY, posZ+9},{posX-4, posY, posZ+9},
                {posX+2, posY, posZ+10},{posX-2, posY, posZ+10},{posX+1, posY, posZ+10},{posX-1, posY, posZ+10}, {posX, posY, posZ+10}
        };
    }
    public void Volcano(){
        double[][] VolcanoEast = {{posX-2, posY, posZ}, {posX-2, posY, posZ+1}, {posX-2, posY, posZ-1},{posX-2, posY, posZ+2}, {posX-2, posY, posZ-2},
                {posX-1, posY, posZ+3}, {posX-1, posY, posZ-3}, {posX-1, posY, posZ+4}, {posX-1, posY, posZ-4},
                {posX, posY, posZ+5}, {posX, posY, posZ-5},
                {posX+1, posY, posZ+5}, {posX+1, posY, posZ-5},
                {posX+2, posY, posZ+6}, {posX+2, posY, posZ-6},
                {posX+3, posY, posZ+6}, {posX+3, posY, posZ-6},
                {posX+4, posY, posZ+6}, {posX+4, posY, posZ-6},
                {posX+5, posY, posZ+6}, {posX+5, posY, posZ-6},
                {posX+6, posY, posZ+6}, {posX+6, posY, posZ-6},
                {posX+7, posY, posZ+5}, {posX+7, posY, posZ-5},
                {posX+8, posY, posZ+5}, {posX+8, posY, posZ-5},
                {posX+9, posY, posZ+4}, {posX+9, posY, posZ-4},
                {posX+10, posY, posZ+2}, {posX+10, posY, posZ-2}, {posX+10, posY, posZ+1}, {posX+10, posY, posZ-1}, {posX+10, posY, posZ}
        };
        double[][] VolcanaWest = {{posX+2, posY, posZ}, {posX+2, posY, posZ+1}, {posX+2, posY, posZ-1},{posX+2, posY, posZ+2}, {posX+2, posY, posZ-2},
                {posX+1, posY, posZ+3}, {posX+1, posY, posZ-3}, {posX+1, posY, posZ+4}, {posX+1, posY, posZ-4},
                {posX, posY, posZ+5}, {posX, posY, posZ-5},
                {posX-1, posY, posZ+5}, {posX-1, posY, posZ-5},
                {posX-2, posY, posZ+6}, {posX-2, posY, posZ-6},
                {posX-3, posY, posZ+6}, {posX-3, posY, posZ-6},
                {posX-4, posY, posZ+6}, {posX-4, posY, posZ-6},
                {posX-5, posY, posZ+6}, {posX-5, posY, posZ-6},
                {posX-6, posY, posZ+6}, {posX-6, posY, posZ-6},
                {posX-7, posY, posZ+5}, {posX-7, posY, posZ-5},
                {posX-8, posY, posZ+5}, {posX-8, posY, posZ-5},
                {posX-9, posY, posZ+4}, {posX-9, posY, posZ-4},
                {posX-10, posY, posZ+2}, {posX-10, posY, posZ-2}, {posX-10, posY, posZ+1}, {posX-10, posY, posZ-1}, {posX-10, posY, posZ}
        };
    }// East & West 10
    public double[][] TownRoadSouth = {{posX, posY, posZ+2}, {posX+1, posY, posZ+2}, {posX-1, posY, posZ+2}, {posX+2, posY, posZ+2}, {posX-2, posY, posZ+2}, {posX+3, posY, posZ+2}, {posX-3, posY, posZ+2},
            {posX+4, posY, posZ-1}, {posX-4, posY, posZ-1}, {posX+5, posY, posZ-1}, {posX-5, posY, posZ-1},

    };
}
